version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: dockerdb
    ports:
      - "5433:5432"
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - .:/data
  api:
    build: ./
    ports:
      - "5000:5000"
    links:
      - "db:database"
    depends_on:
        - db
    restart: on-failure:2
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        FLASK_APP: ${FLASK_APP}
        FLASK_RUN_HOST: ${FLASK_RUN_HOST}
        FLASK_RUN_PORT: ${FLASK_RUN_PORT}
        FLASK_ENV: ${FLASK_ENV}
    volumes:
      - .:/apidata