version: "3.3"

services:
  postgres:
    build: ./db
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build: ./src
    container_name: api
    volumes:
      - ./src:/usr/src
    ports:
      - 5000:5000
    networks:
      - net
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgres:postgres@postgres:5432/db_dev
      - DATABASE_TEST_URL=postgres:postgres@postgres:5432/db_test
    depends_on:
      - postgres
    links:
      - postgres
    command: gunicorn --worker-class eventlet -w 4 --preload -b 0.0.0.0:5000 manage:app

volumes:
  postgres:

networks:
  net:
