version: '3.3'

services:
    postgres:
      build: ./db
      container_name: postgres
      ports:
        - 5433:5432
      networks:
        - net
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
        - postgres:/var/lib/postgresql/data

    flask:
      build: ./flask
      container_name: flask
      volumes:
        - ./flask:/usr/src/app
      networks:
        - net
      environment:
        - APP_SETTINGS=config.DevelopmentConfig
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/db_dev
        - DATABASE_TEST_URL=postgresql://postgres:postgres@postgres:5432/db_test
      depends_on:
        - postgres
      links:
        - postgres
      command: gunicorn --worker-class eventlet -w 4 -b 0.0.0.0:8000 manage:app

volumes:
  postgres:

networks:
  net: