#!/usr/bin/env bash
export POSTGRES_USER=dockerdb
export POSTGRES_PASSWORD=dockerdb
export POSTGRES_HOST=dockerdb
export POSTGRES_PORT=5433
export POSTGRES_DB=dockerdb
export FLASK_APP=./src/api/index.py
export FLASK_RUN_HOST=0.0.0.0
export FLASK_RUN_PORT=5000
export FLASK_ENV=development